import type { GetStaticProps, NextPage } from 'next'
import Head from 'next/head'

import { Badge, createTheme, CssBaseline, Divider, PaletteMode, ThemeProvider, Typography, useTheme } from '@mui/material'
import MailIcon from '@mui/icons-material/Mail'

import { Box } from '@mui/system'

import { GetStaticPaths, InferGetStaticPropsType } from "next"

import fs from 'fs';
import path from 'path';

import matter from 'gray-matter';

import { serialize } from 'next-mdx-remote/serialize'

import {MDXRemote, MDXRemoteSerializeResult} from 'next-mdx-remote'

import typescript from 'highlight.js/lib/languages/typescript'

import 'highlight.js/styles/vs2015.css'
import hljs from "highlight.js";
import { useEffect } from "react";
import { Post } from '../models/Post.interface'
import CardComponent from '../components/Card.component'

const Home: NextPage = ({ posts } : InferGetStaticPropsType<typeof getStaticProps>) => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box display = 'flex' justifyContent='center' alignItems='center' minHeight='100vh'>
      <div>
        <Badge badgeContent={1} color="primary">
          <MailIcon/>
        </Badge>
        <Badge badgeContent={2} color="secondary">
          <MailIcon/>
        </Badge>
        <Badge badgeContent={3} color="info">
          <MailIcon/>
        </Badge>
        <Badge badgeContent={4} color="warning">
          <MailIcon/>
        </Badge>
        <Badge badgeContent={5} color="error">
          <MailIcon/>
        </Badge>
        <Badge badgeContent={5} color="success">
          <MailIcon/>
        </Badge>
        <div style={{ height: '400px', }}>
          <Typography color='primary' variant='h1'>Avatar Legends</Typography>
          <Typography color='secondary' variant='h3'>Content Management System</Typography>
          <Divider/>
          <Typography variant='h4'>Hello!</Typography>
        </div>
        <p>This is the first page and a draft go away.</p>
      </div>
    </Box>
    <div>
      {posts.map((post: Post, index: number) => (<CardComponent key={index} post={post}/>))}
    </div>
    </div>
  )
}

export default Home

export const getStaticProps: GetStaticProps = async () => {

  const articlesDirectory = path.join('articles');
  const files = fs.readdirSync(articlesDirectory);

  const blogPosts = files.map((fileName: string) => {
    const slug = fileName.replace('.mdx', '');
    const article = fs.readFileSync(path.join('articles', fileName));
    const { data: metaData } = matter(article);
    return {slug, metaData}
  });

  return {
      props: {posts: blogPosts }
  }
}